#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

enum custom_keycodes {
    GOINFOLOG = SAFE_RANGE,
		GOERR
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT_reviung39(LALT_T(KC_ESC), KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
		LCTL_T(KC_LPRN), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT,
		LSFT_T(KC_RPRN), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, RSFT_T(KC_ENT),
		LT(1,KC_TAB), KC_SPC, LT(2,KC_BSPC)),
	[1] = LAYOUT_reviung39(KC_TRNS, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL,
		KC_TRNS, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_GRV, KC_TILD,
		KC_TRNS, KC_ESC, KC_LGUI, KC_LALT, KC_CAPS, KC_DQUO, KC_HOME, KC_END, KC_PGUP, KC_PGDN, KC_PSCR, RSFT_T(KC_SPC),
		KC_TRNS, KC_ENT, MO(3)),
	[2] = LAYOUT_reviung39(KC_TRNS, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL,
		KC_TRNS, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6,
		KC_TRNS, KC_ESC, KC_RGUI, KC_RALT, KC_CAPS, KC_QUOT, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12,
		MO(3), KC_BSPC, KC_LGUI),
	[3] = LAYOUT_reviung39(RGB_VAI, RGB_SAI, RGB_HUI, RGB_SPI, RGB_M_X, RGB_TOG, RESET, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		RGB_VAD, RGB_SAD, RGB_HUD, RGB_SPD, RGB_M_G, RGB_M_T, KC_WH_U, KC_WH_D, KC_WH_L, KC_WH_R, KC_MUTE, KC_NO,
		MO(4), RGB_M_P, RGB_M_B, RGB_M_R, RGB_M_SN, RGB_M_K, KC_VOLD, KC_VOLU, KC_MRWD, KC_MPLY, KC_MFFD, MO(4),
		KC_TRNS, KC_NO, KC_TRNS),
	// Code/macro layers
	[4] = LAYOUT_reviung39(KC_NO, KC_NO, KC_NO, GOERR, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, GOINFOLOG, KC_NO, KC_NO,
		KC_TRNS, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
		KC_NO, KC_NO, KC_NO)
};


bool process_record_user(uint16_t keycode, keyrecord_t *record) {
    switch (keycode) {
    case GOINFOLOG:
        if (record->event.pressed) {
            // when keycode QMKBEST is pressed
            SEND_STRING("log.Info().Msgf(");
        } else {
            // when keycode QMKBEST is released
        }
        break;
		case GOERR:
				if (record->event.pressed) {
					SEND_STRING("if err != nil {\n\t");
				} else {
					// nothing on release
				}
    }
    return true;
};
